### ISSUE TITLE
Failure to produce graphs in the QC interface when analyzing less than 4 plates.

### ISSUE THREAD

**Issue by hanna-alalam** [local-minimum/scanomatic#99] opened 2017-02-09 10:13 UTC
Graphs do not show up in QC if you run less than 4 plates. I have done this with 2 plates (in the fixture only two plates were selected). also for some reason it indicates the presence of a third and fourth plate even if they were not marked in the fixture.
![screenshot from 2017-02-09 11 10 11](https://cloud.githubusercontent.com/assets/25660289/22778855/b1d6ed4a-eeb8-11e6-90ab-3a3e508d5723.png)
![screenshot from 2017-02-09 11 12 08](https://cloud.githubusercontent.com/assets/25660289/22778866/c126f894-eeb8-11e6-8e78-a2e9412f0459.png)

**Comment by hanna-alalam** [comment] 2017-02-09 15:12
Update: selecting all 4 plates when making the filter and analyzing allowed the graphs to display but they disappeared again after regridding the plate.

**Comment by Endimion75** [comment] 2017-02-10 07:45
@local-minimum is there a way I could get some data for an experiment with 2 plates or something similar? So I can debug this scenario?

**Comment by local-minimum** [comment] 2017-02-10 08:30
I think it best if @hanna-alalam made a zip of the project, but lets not do it through here since the project contains unpublished data. I'll take mail both of you.

The issue should be reproducible for any project if you make a new fixture that only holds 2 plates and then redo the compilation and analysis.

**Comment by Endimion75** [comment] 2017-02-10 08:32
I will try to do the fixture thing as a first step and see if that works for me

**Comment by local-minimum** [comment] 2017-02-13 15:56
We've discovered that this is in fact two separate issues #101 and #102, this issue is therefore closed and resolving moved to the two new.

**Closed by local-minimum** 2017-02-13 15:56 UTC
Labels: bug, UI
